version: '3.3'
services:
  server:
    image: node:16-alpine
    container_name: server
    command: sh -c "yarn install  && yarn build && yarn start"
    volumes:
      - ./:/server
    working_dir: /server
    ports:
      - '3080:3080'
    restart: 'always'
    networks:
      - webproxy
  # redis:
  #   image: 'redis:5.0.8-alpine'
  #   container_name: 'redis'
  #   ports:
  #     - 6379:6379
  #   healthcheck:
  #     test: ['CMD-SHELL', "sh -c 'redis-cli PING'"]
  #     interval: 30s
  #     timeout: 30s
  #     retries: 3
  #   restart: 'on-failure'
  #   networks:
  #     - webproxy
networks:
  webproxy:
    driver: bridge
