name: server
on:
  push:
    branches: ['main']
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout/@v2


    # - name: Start Deployment
    #   uses: TapTap21/docker-remote-deployment-action@v1.0
    #   with:
    #     remote_docker_host: ${{secrets.GOOGLE_CLOUD_HOST}}
    #     ssh_private_key:  ${{secrets.SSH_PRIVATE_KEY}}
    #     ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
    #     stack_file_name: docker-compose.yml
    #     docker_login_password: Hoainhon181120@#
    #     docker_login_user: abeesdevjs
    #     docker_login_registry : ${{ steps.login-ecr.outputs.registry }}
    #     args: -p myapp up -d

     - uses: alex-ac/github-action-ssh-docker-compose@master
      name: Docker-Compose Remote Deployment
      with:
        ssh_host: ${{secrets.GOOGLE_CLOUD_HOST}}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh_user: ${{ secrets.SSH_USER_NAME }}
        docker_compose_prefix: server
    
      # - name: Login Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: abeesdevjs
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # - name: Setup Docker Build
      #   uses: docker/setup-buildx-action@v1
      #   id: buildx
      # - name: Build and Push Docker
      #   uses: docker/build-push-action@v2
      #   id: docker_build
      #   with:
      #     context: ./
      #     file: ./Dockerfile
      #     builder: ${{ steps.buildx.outputs.name }}
      #     push: true
      #     tags: abeesdevjs/server
      # - name: SSH Remote google cloud and run Docker
      #   uses: appleboy/ssh-action@v0.1.2
      #   with:
      #     key: ${{secrets.SSH_PRIVATE_KEY}}
      #     host: ${{secrets.GOOGLE_CLOUD_HOST}}
      #     username: ${{secrets.SSH_USER_NAME}}
      #     script: |
      #       sudo docker pull abeesdevjs/server:latest 
      #       sudo docker rm -f server
      #       sudo docker run --name server -dp 3030:3030 abeesdevjs/server
